name: VBA GX Build

on: [push, pull_request]

jobs:
  build:
    name: Build VBA GX
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        image: ["Wii", "GameCube"]
    container: devkitpro/devkitppc:latest
 
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: true

    - name: Build Wii
      if: ${{ matrix.image == 'Wii' }}
      run: |
        make -f Makefile.wii -j2
    
    - name: Copy Wii artifact
      if: ${{ matrix.image == 'Wii' }}
      run: | 
        mkdir -p dist/VisualBoyAdvanceGX/apps/vbagx
        mkdir -p dist/VisualBoyAdvanceGX/vbagx/roms
        mkdir dist/VisualBoyAdvanceGX/vbagx/saves
        touch dist/VisualBoyAdvanceGX/vbagx/roms/romsdir
        touch dist/VisualBoyAdvanceGX/vbagx/saves/savesdir
        cp hbc/* dist/VisualBoyAdvanceGX/apps/vbagx/
        cp executables/vbagx-wii.dol dist/VisualBoyAdvanceGX/apps/vbagx/boot.dol

    - name: Upload Wii artifacts
      uses: actions/upload-artifact@v2
      if: ${{ matrix.image == 'Wii' }}
      with: 
        name: VisualBoyAdvanceGX
        path: |
         dist/VisualBoyAdvanceGX/
         
    - name: Build GameCube
      if: ${{ matrix.image == 'GameCube' }}
      run: |
        make -f Makefile.gc -j2
        
    - name: Copy GameCube artifact
      if: ${{ matrix.image == 'GameCube' }}
      run: | 
        mkdir -p dist/VisualBoyAdvanceGX-GameCube
        cp executables/vbagx-gc.dol dist/VisualBoyAdvanceGX-GameCube/
    
    - name: Upload GameCube artifact
      uses: actions/upload-artifact@v2
      if: ${{ matrix.image == 'GameCube' }}
      with: 
        name: VisualBoyAdvanceGX-GameCube
        path: |
         dist/VisualBoyAdvanceGX-GameCube/
